server:
  port: 8082
  use-forward-headers: true

spring:
  boot:
    admin:
      monitor:
        read-timeout: 20000
      notify:
        mail:
          from: luojiawei0078@126.com
          to: 584198437@qq.com
  security:
    user:
      name: admin
      password: admin
  mail:
    host: smtp.126.com
    username: luojiawei0078@126.com
    password: ljw930824
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  thymeleaf:
    check-template-location: false